# Mnemonics extracted from Cendrillon palikA (Switch, Japan)

mnemonics:
  #Return: 0
  return: 0  # I like the lowercase more lol
  Next: 2
  Mif: 3
  Mif4: 4 # Both 3 and 4 are called Mif, and point to the same function. Only 3 is used.
  Loop: 5
  goto: 6
  Wait: 7
  WaitNoSlow: 8
  M_Push: 0x11
  M_Pop: 0x12
  DebugPrint_Word: 0x3c
  DebugPrint_Int: 0x3d
  DebugPrint_Float: 0x3e
  DebugPrint_Float4: 0x3f
  DebugPrint_Float3: 0x40
  ErrorPrint_Word: 0x41
  ErrorPrint_Int: 0x42
  ErrorPrint_Float: 0x43
  ErrorPrint_Float4: 0x44
  ErrorPrint_Float3: 0x45
  DebugPrint_Lon: 0x46
  strcpy: 0x50
  strcat: 0x51
  strcat_Int: 0x52
  sin: 100
  cos: 0x65
  tan: 0x66
  atan2: 0x67
  Rand: 0x6e
  GetRand_In: 0x6f
  GetRand_Float: 0x70
  AddRand_Int: 0x71
  AddRand_Float: 0x72
  GetDistance2D: 0x73
  GetDistance3D: 0x74
  Get2PosToRot: 0x75
  PosRotToPos: 0x76
  JS_Free: 0xe6
  JS_FreeJoint: 0xe7
  JS_SetThreadMode: 0xee
  JS_SetThreadModeThreadGroup: 0xef
  JS_SetValue: 0xf0
  JS_GetValue: 0xf1
  JS_CopyValue: 0xf2
  JS_ChangeAnim: 0xf3
  JS_ChangeAnimSpeed: 0xf4
  JS_ChangeDrawMode: 0xf5
  JS_ChangeConverterMode: 0xf6
  JS_SetParent: 0xf7
  JS_GetGlobalPos: 0xf8
  JS_SetThreadModeGroup: 0xf9
  JS_GetGlobalRot: 0x118
  JS_GetGlobalScale: 0x119
  JS_GetGlobalColor: 0x11a
  CW_Play: 0x11d
  JSA_CWD: 0x11e
  JS_SetNoSlowFlag: 0x11f
  JS_CW_SetNoSlowFlag: 0x140
  JS_CW_RunWait: 0x120
  JS_CW_IsRun: 0x121
  JS_CW_SetObjectFlag: 0x122
  JS_CW_SetControlFlag: 0x123
  JS_CW_GetControlFlag: 0x124
  JS_CW_SearchObjectThread: 0x125
  JS_SetRunType: 0x127
  JS_FreeParent: 0x128
  JS_CW_SetObjectFlagThread: 0x126
  JS_CW_GetObjectFlagThread: 0x129
  JS_CW_SetGlobalFlag: 0x12a
  JS_CW_GetGlobalFlag: 299
  JSA_SimplePolygon2D: 0xfa
  JSA_MGP2: 0xfd
  JSA_SimplePolygon3D: 0xfe
  JSA_AfterImage: 0xff
  JSA_SimplePolygonBG: 0x101
  JSA_MoveLine: 0x104
  JSA_MoveAB: 0x105
  JSA_MoveInfinite: 0x106
  JSA_LookRot: 0x107
  JSA_AngleMode: 0x108
  JSA_MoveJump: 0x109
  JSA_PosLookRot: 0x10a
  JSA_MoveDirection: 0x10b
  JSA_MoveWait: 0x10c
  JSA_MoveWaitAll: 0x10d
  JS_GetSoundInstallNo: 300
  JS_PlaySE: 0x12d
  JS_PlayBGM: 0x12e
  JS_PlayVOICE: 0x12f
  JS_SetSoundPosition: 0x131
  JS_MemPlaySE: 0x136
  JS_FadeVolume: 0x137
  JS_FadeVolumeAutoFree: 0x138
  JS_SoundHandleIsPlaying: 0x139
  JS_SetJSHTUM_Mode: 0x149
  GetMyId: 200
  Create: 0xc9
  Free: 0xca
  GroupFree: 0xcb
  ChangeOrder: 0xcc
  GetGroupThread: 0xcd
  GetOrder: 0xce
  SetRegisterInt: 0xd2
  SetRegisterFloat: 0xd3
  GetRegisterInt: 0xd4
  GetRegisterFloat: 0xd5
  SetRegisterLong: 0xd6
  GetRegisterLong: 0xd7